repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.4  # Sostituisci con la versione desiderata
    hooks:
      - id: clang-format
        args: ["--style=file", "--verbose"]  # Usa un file .clang-format nella root del progetto

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]
        files: \.md$